version: "3.9"
services:
  postgres:
    image: postgres:12.19-alpine3.20
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"